### ISSUE TITLE
ビューテンプレにslimを検討

### ISSUE THREAD

**Issue by kayhide** [flightcity/crowdfunding#15]
http://slim-lang.com/

**Comment by kayhide** [comment]
@flightcity このイシューを早めに検討することをオススメします。
デフォルトのerbよりslimを使った方が、ビューのコーディングが格段に楽になりますので。

**Comment by flightcity** [comment]
次は、このイシューに取り組みます。

**Comment by kayhide** [comment]
:+1:

**Comment by kayhide** [comment]
対応したのでクローズしてくださいませ。
