### ISSUE TITLE
テストを書く

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#18]
テストを書くようにする。

**Comment by flightcity** [comment]
bundle exec guard start
でテストを起動しました。

ペンディング
・テストの書き方
・bin/rails s でサーバも同時に起動したい

**Comment by kayhide** [comment]
目安）
まずは、models と controllers だけテストするのがよいです。
routing や views などは、テストコスパがよくないので。

```
    config.generators do |g|
      ...
      g.test_framework :rspec, fixture: true, fixture_replacement: :factory_girl
      g.view_specs false
      g.routing_specs false
      g.request_specs false
    end
```

**Comment by kayhide** [comment]
そして、カバレッジ（テストがコードのどれくらいをカバーしているか）を計測しましょう。
https://github.com/colszowka/simplecov

models と controllers のカバレッジが100%になればOKです。
今後もとくに理由がない限り、カバレッジ100%をキープしましょう。

**Comment by kayhide** [comment]
> ・bin/rails s でサーバも同時に起動したい

これは別イシューにした方がよいかな。

**Comment by kayhide** [comment]
このイシューは終わりがないのでクローズしましょう。

「xxxのテストを書く」みたいに具体的な作業であれば、イシューにしましょう。

**Comment by flightcity** [comment]
了解しました。
クローズします。
