### ISSUE TITLE
自動テストと開発用サーバを同時に起動する

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#19]
システムの開発自体とは直接関係が無いので恐縮ですが・・・
bundle exec guard start
でguardを起動しつつ
bin/rails s
でサーバも同時に起動したいです。

**Comment by kayhide** [comment]
そういうのでも大丈夫です。
開発用のイシューとまざってしまうのが気になるようでしたら、それ用の label を作ってイシューに設定しておくとよいです。

**Comment by kayhide** [comment]
こんなのはどうでしょう？

tmux
http://qiita.com/b4b4r07/items/01359e8a3066d1c37edc
http://girigiribauer.com/archives/1716

ワンコマンドでwindowとかpaneを開きつつ特定のコマンドを実行する、とかできそうです。

**Comment by kayhide** [comment]
参考までに、mac なら pow というサーバーが使えます。
http://doruby.kbmj.com/oneafter999_on_rails/20141022/Rails_Rack_Pow_

これなら、`rails s` を打つ必要はないです。

**Comment by flightcity** [comment]
昨日、macが届きまして。
変換ケーブルが必要な事が発覚したため、注文中です。
改めて、macで開発環境を構築してから開発再開します。

**Comment by kayhide** [comment]
了解ですー。

**Comment by flightcity** [comment]
powサーバ、凄くいいです。
さすが、macだとゴキゲンな開発環境が整っていますね。
powサーバの導入で問題が解決したのでcloseします。
ありがとうございました。

**Comment by kayhide** [comment]
mac 導入、お疲れ様です。
mac がゴキゲンというか win がフキゲンというような気もしますがw

pow を使うのにこれ↓も併用するとよりよいですよ。
https://github.com/Rodreegez/powder
