### ISSUE TITLE
機能拡張予定

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#2]
・商品画像（商品と1対多）もモデルとコントローラ類を追加
・商品への投資（？）（商品と1対多）もモデルとコントローラ類を追加
・管理者アカウント・ユーザアカウントのモデルとコントローラ類を追加
・会員登録のコントローラ類を作成
・ユーザアカウントから商品への投資をするコントローラを作成
・管理画面のデザインを何とかする
・公開画面のデザインを何とかする

とりあえず、このような感じです。

**Comment by kayhide** [comment]
#3 #4 #5 #6 #7 #8 #9 #10 に分割。

**Comment by flightcity** [comment]
イシューを分割するためclose
