### ISSUE TITLE
リダイレクト前のdbアクセスを回避。

### ISSUE THREAD

**Issue by kayhide** [flightcity/crowdfunding#28]
https://github.com/flightcity/crowdfunding/blob/master/app/controllers/admin/products_controller.rb#L6-L9

リダイレクトしてしまうと、`find` のdbアクセスが無駄になるのでこのようにするのがよいです。

```ruby
redirect_to edit_admin_product_url(params[:id])
```

**Comment by flightcity** [comment]
#29 で解決したのでcloseしますか？

**Comment by kayhide** [comment]
クローズしてくださいませ。
