### ISSUE TITLE
商品画像のモデルとコントローラ類を追加

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#3]
商品と商品画像は1対多の関係
商品に対して商品画像を登録できるようにする

**Comment by kayhide** [comment]
画像を扱うには定番の gem がいくつかあります。
- [CarrierWave](https://github.com/carrierwaveuploader/carrierwave)
- [PaperClip](https://github.com/thoughtbot/paperclip)
- [DragonFly](https://github.com/markevans/dragonfly)

**Comment by kayhide** [comment]
まずは、どれを使うか決めましょう。
それぞれの特徴というか個人的な経験談はこんな感じです。

**CarrierWave**
PaperClip と大差ない（と思う）
どういうわけかチュートリアルでとりあげられていることが多い。

**PaperClip**
老舗。
github のスター数もこの3つで最も多い。
保守的にいくならこれ。

**DragonFly**
後発。
オンザフライ処理ができる。
アグレッシブにいくならこれ。

**Comment by flightcity** [comment]
feature/product-images にて実装済み。

**Comment by kayhide** [comment]
実装済なのでクローズしてくださいませ。
