### ISSUE TITLE
アカウントの種別を管理者・出品者・入札者の3種類にする

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#30]
フラグ管理すると、出品者かつ入札者といったアカウント管理が可能になる

**Comment by kayhide** [comment]
出品者、入札者は分ける必要がありますかね？

一般ユーザーは全員、出品も入札もできる、
にした場合とどのような違いが想定されますでしょうか？

**Comment by flightcity** [comment]
出品者はクローズドで募集するとの事でしたので、自由に登録できてよいものか・審査等は必要ないかと思いました。
出品も入札と同じように自由に行えれば、問題ないと思います。

**Comment by kayhide** [comment]
そうですね。
ではまずは、出品者、入札者をまとめて一般ユーザーとしてしまいましょうか。
一般ユーザーには、全員入札と出品の権限を与える、というかたちにしましょう。

それで問題がでてくるようなら、あとから出品権限のような機能を追加してコントロールすればよさそうですね。

**Comment by flightcity** [comment]
了解しました！
管理者・一般ユーザの区分は既に実装されていますので、このissueは不要と言うことでcloseしますね。
