### ISSUE TITLE
入札者アカウント管理

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#32]
現在の一般ユーザ管理を流用する
規約に同意が必要かもです

**Comment by kayhide** [comment]
規約はいずれは必要ですね。
別イシューにしましょう。

**Comment by kayhide** [comment]
このイシューをどう扱うかは出品者、入札者の仕様次第ですね。
#30

**Comment by flightcity** [comment]
出品者ユーザと入札者ユーザを分けないようにしたため、#39に統一してcloseます。
