### ISSUE TITLE
商品への投資のモデルを追加

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#4]
商品と商品への投資は1対多の関係
「商品への投資」は仮名

**Comment by kayhide** [comment]
投資にはどのユーザーからのものかという関連も必要ですね。
なので、

User has_many investments
Product has_many investments

Investment belongs_to user
Investment belongs_to product

な感じになるかな。

**Comment by flightcity** [comment]
#22 で解決したのでcloseしますか？

**Comment by kayhide** [comment]
クローズしましょう。
