### ISSUE TITLE
会員登録のコントローラ類を作成

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#7]
ユーザが会員登録・変更・削除できるようにする
管理者側からもユーザのCRUDをできるようにする

**Comment by kayhide** [comment]
これは、ふたつ別々のissueに分けたほうがよさそうですね。

ユーザーが自分で何かをやるための機能と
管理者が何かをやるための機能
は別々に作るものになりますので。

**Comment by flightcity** [comment]
#11 #12に分割しました。
