### ISSUE TITLE
管理画面のデザインを何とかする

### ISSUE THREAD

**Issue by flightcity** [flightcity/crowdfunding#9]

**Comment by kayhide** [comment]
定番のデザイン用フレームワーク。
http://getbootstrap.com/

gem
https://github.com/twbs/bootstrap-sass

ついでにアイコンはこれ。
http://fortawesome.github.io/Font-Awesome/

gem
https://github.com/bokmann/font-awesome-rails

**Comment by kayhide** [comment]
デザイン、こちらの方で少しやってみましょうか？
その方がbootstrap流の書き方が効率よく把握できると思いますが、いかがでしょう？

**Comment by flightcity** [comment]
管理画面のデザイン改良を #27 で実装しました。closeします。
